// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: c48ffb9f04
// Version Date: Wed Aug 12 00:08:17 UTC 2020

// Package grpc provides a gRPC client for the LotteryService service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/thebinarytrio/weighted-lottery/backend"
	"github.com/thebinarytrio/weighted-lottery/backend/lotteryservice-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.LotteryServiceServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var lotteryserviceEndpoint endpoint.Endpoint
	{
		lotteryserviceEndpoint = grpctransport.NewClient(
			conn,
			"lotteryService.LotteryService",
			"LotteryService",
			EncodeGRPCLotteryServiceRequest,
			DecodeGRPCLotteryServiceResponse,
			pb.AllEventsResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		LotteryServiceEndpoint: lotteryserviceEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCLotteryServiceResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC lotteryservice reply to a user-domain lotteryservice response. Primarily useful in a client.
func DecodeGRPCLotteryServiceResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.AllEventsResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCLotteryServiceRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain lotteryservice request to a gRPC lotteryservice request. Primarily useful in a client.
func EncodeGRPCLotteryServiceRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.AllEventsRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
