FROM mysql:8.0 
ENV MYSQL_ALLOW_EMPTY_PASSWORD yes  
ADD setup.sql /docker-entrypoint-initdb.d/

# REFERENCE: https://hub.docker.com/_/mysql/ 
# environment variables and initializing a fresh instance 
# use shift+ command + p to open all of the docker commands

