name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'
      - name: build
        workspace: weighted-lottery/rest-api-backend/main.go
        run: go build -o weighted-lotty
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: go formatting
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: fmt